### ISSUE TITLE
How to use from a vuex store (or other .js files) ?

### ISSUE THREAD

**Issue by kirianguiller** [KanHarI/vue3-cookies#3]
Hi everyone, thanks for this plugin.

I was wondering how to use from a vuex store (or other .js files) ? Indeed, in the store, `this` is not available.

Thanks !

**Comment by gewisser** [comment]
Hi!
try it:

1. Create plugin, example `cookies.js`
```javascript
import VueCookies from 'vue3-cookies'

let $cookies

export default (app) => {
  VueCookies.install(app);
  $cookies = app.config.globalProperties.$cookies
};

export { $cookies }
```
2. init plugin:
```javascript
import { createApp } from 'vue'
import MyApp from './MyApp.vue'
import cookiesInit from './cookies'

const app = createApp(MyApp)
cookiesInit(app)

app.mount('#app')
```

3. in composition module:
```javascript
import { $cookies } from './cookies'

$cookies.set('theme','default');
$cookies.set('hover-time','1s');
```

**Comment by kevinmlong** [comment]
Does this actually work?

Following the above example, I'm seeing that `$cookies` is undefined in the composition module

**Comment by kirianguiller** [comment]
Hey, thank you, I did this and it works perfectly !

Here is the place I initiated it : https://github.com/Arborator/arborator-frontend/blob/quasar_v2/src/boot/vue-cookies.js

And here where I used it in the store : https://github.com/Arborator/arborator-frontend/blob/7e45820d1a59bae0ac3248c77064c36efdf89016/src/store/modules/user/index.js#L47

**Comment by kirianguiller** [comment]
Hey, it worked really fine for me. You need to check if the app is well
initiated .
In the GitHub issue, i linked to my vue app where I used it (and made it
works).

Thanks !

Kirian
